language: cpp
sudo: required
dist: trusty
services:
  - redis-server
env:
  global:
    - secure: chPYEImsxltrhw/k3DTYTI0oaQwnJSqFc7wqNcJwJaZSPCaHh5KWOPSxNtqwvLsvLBDFKiicsVfTLcectLRnt1jV7zjDQev5/GmCIstKuU6vpG5EXezRJADkSJEli9OTt9wjuHPJhibUCihvmv6WW87BcEUA1936J1EDzfZWKDLc6I5xiLYHxE2JGf6/tKrJ2G7NXYkriPvo0986kekMwcovGeaQkNEHMYn5TcDkKR79Mmz8Pd50+SfV55jZo6a7qOxr3kLAUSQ6CMb5wUkzKO6qL3OB+CwohXmqMQlvsOn9VBdNT/O6R+5MLCFzgt46phAQAonI+OBSmMiEg3KeNSaZ+g007mWKYRlMK4ZvaooyHVoT0RqtvICDADKYjB2Iea5ajZFBGhXrW/+u1WKEPNc2txZKE/xndgMf2s0R7NYWSEcJrdVBYtgxYy0OPKdDi4Va75oZ5eFMWBlUHCOSEILiNDmCKH4RPOw2zrdL72zbb9OLLys2NuM0MsMtnsKWXnVQ9CRXyzm8iZtvG7ZExG5ePO3OzwFB02nB4cLM9cClw5/0ofvG8kQ44IwANUS3M9TwKnoHm6hUZqhSnEtdeUye5ebMMCVv+ZdM/LX02/Hso3MqoJfx0IdpnYbgvRCy8zJWxEdwJn2pC4BoQawJx8OgNSx9cjCuy6AH93q2zcQ=
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - libboost-dev
            - libboost-date-time-dev
            - libboost-regex-dev
            - build-essential
            - liblua5.1-0-dev
            - python-virtualenv
            - python-bottle
            - libgeoip-dev
            - geoip-database
            - cpanminus
            - libprotobuf-dev
            - protobuf-compiler
            - libhiredis-dev
            - libcurl4-openssl-dev
            - redis-server
            - libyaml-cpp-dev
            - wget
      env:
        - MYCXX=g++
        - MYCC=gcc
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - libboost-dev
            - libboost-date-time-dev
            - libboost-regex-dev
            - build-essential
            - liblua5.1-0-dev
            - python-virtualenv
            - python-bottle
            - libgeoip-dev
            - geoip-database
            - cpanminus
            - libprotobuf-dev
            - protobuf-compiler
            - libhiredis-dev
            - libcurl4-openssl-dev
            - redis-server
            - libyaml-cpp-dev
            - wget
      env:
        - MYCXX=clang++-4.0
        - MYCC=clang-4.0
before_script:
 - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install systemd-services libsystemd-daemon-dev libsystemd-daemon0
 - wget http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium-dev_1.0.0-1_amd64.deb http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium13_1.0.0-1_amd64.deb
 - dpkg-deb -x libsodium13_1.0.0-1_amd64.deb ${HOME}/libsodium
 - dpkg-deb -x libsodium-dev_1.0.0-1_amd64.deb ${HOME}/libsodium
 - rm libsodium13_1.0.0-1_amd64.deb libsodium-dev_1.0.0-1_amd64.deb
 - sed -i -e "s@/usr@${HOME}/libsodium/usr@" ${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig/libsodium.pc
 - export PKG_CONFIG_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig
 - export LD_LIBRARY_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu
 - echo "deb http://cz.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
 - sudo apt update -qq
 - sudo apt install libgetdns-dev -y
 - dig @208.67.222.222 a.root-servers.net
 - cpanm --quiet --installdeps --notest Template
 - cpanm --quiet --installdeps --notest Swagger2::Markdown
 - sudo wget -N -O /usr/share/GeoIP/GeoIPCityv6.dat.gz http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
 - sudo gunzip /usr/share/GeoIP/GeoIPCityv6.dat.gz
 - sudo wget -N -O /usr/share/GeoIP/GeoIPCity.dat.gz http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
 - sudo gunzip /usr/share/GeoIP/GeoIPCity.dat.gz
script:
 - autoreconf -i
 - ./configure --enable-docker CC=$MYCC CXX=$MYCXX
 - make
 - cd regression-tests
 - ./runtests
 - cd ..
 - cd docker
 - make
 - cd ..
 - export WF_VERSION=`grep PACKAGE_VERSION Makefile | awk  '{ print $3}'`
 - git status
 - git status | grep -q clean
 - make dist
 - tar xvf wforce-$WF_VERSION.tar.gz
 - cd wforce-$WF_VERSION
 - autoreconf -i
 - cd ..
 - mkdir build
 - cd build
 - ../wforce-$WF_VERSION/configure CC=$MYCC CXX=$MYCXX
 - make
 - cd ..
 - make distcheck
 - ./trigger__policy_build.sh
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
