language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost-dev
      - gcc-5
      - g++-5
      - libstdc++-5-dev
      - liblua5.1-0-dev
      - python-virtualenv
      - libgeoip-dev
      - geoip-database
    sources:
      - ubuntu-toolchain-r-test
before_script:
 - wget http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium-dev_1.0.3-1_amd64.deb http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium13_1.0.3-1_amd64.deb
 - dpkg-deb -x libsodium13_1.0.3-1_amd64.deb ${HOME}/libsodium
 - dpkg-deb -x libsodium-dev_1.0.3-1_amd64.deb ${HOME}/libsodium
 - rm libsodium13_1.0.3-1_amd64.deb libsodium-dev_1.0.3-1_amd64.deb
 - sed -i -e "s@/usr@${HOME}/libsodium/usr@" ${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig/libsodium.pc
 - export PKG_CONFIG_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig
 - export LD_LIBRARY_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu
 - wget http://http.us.debian.org/debian/pool/main/g/getdns/libgetdns1_0.5.1-1_amd64.deb http://http.us.debian.org/debian/pool/main/g/getdns/libgetdns-dev_0.5.1-1_amd64.deb
 - dpkg-deb -x libgetdns-dev_0.5.1-1_amd64.deb ${HOME}/getdns
 - dpkg-deb -x libgetdns1_0.5.1-1_amd64.deb ${HOME}/getdns
 - rm libgetdns-dev_0.5.1-1_amd64.deb libgetdns1_0.5.1-1_amd64.deb
 - mkdir -p ${HOME}/getdns/usr/local/lib/pkgconfig
 - echo -e "prefix=${HOME}/usr/local\nexec_prefix=${prefix}\nlibdir=${exec_prefix}/lib\nincludedir=${prefix}/include\n\nName: getdns\nVersion\: 0.5.1\nDescription\: A modern asynchronous DNS library\n\nLibs\: -L${libdir} -lgetdns\nCflags\: -I${includedir}\n" >${HOME}/getdns/usr/local/lib/pkgconfig
 - export PKG_CONFIG_PATH=${HOME}/getdns/usr/local/lib/pkgconfig
 - export LD_LIBRARY_PATH=${HOME}/getdns/usr/local/lib/
script:
 - export CC='gcc-5' CXX='g++-5'
 - autoreconf -i
 - ./configure
 - make
 - cd regression-tests
 - ./runtests
 - git status
 - git status | grep -q clean
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
