language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
services:
  - redis-server
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-date-time-dev
      - libboost-regex-dev
      - build-essential
      - liblua5.1-0-dev
      - python-virtualenv
      - python-bottle
      - libgeoip-dev
      - geoip-database
      - cpanminus
      - libprotobuf-dev
      - protobuf-compiler
      - libhiredis-dev
      - libcurl4-openssl-dev
      - redis-server
      - libyaml-cpp-dev
      - wget
before_script:
 - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install systemd-services libsystemd-daemon-dev libsystemd-daemon0
 - wget http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium-dev_1.0.0-1_amd64.deb http://http.us.debian.org/debian/pool/main/libs/libsodium/libsodium13_1.0.0-1_amd64.deb
 - dpkg-deb -x libsodium13_1.0.0-1_amd64.deb ${HOME}/libsodium
 - dpkg-deb -x libsodium-dev_1.0.0-1_amd64.deb ${HOME}/libsodium
 - rm libsodium13_1.0.0-1_amd64.deb libsodium-dev_1.0.0-1_amd64.deb
 - sed -i -e "s@/usr@${HOME}/libsodium/usr@" ${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig/libsodium.pc
 - export PKG_CONFIG_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu/pkgconfig
 - export LD_LIBRARY_PATH=${HOME}/libsodium/usr/lib/x86_64-linux-gnu
 - echo "deb http://cz.archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
 - sudo apt update -qq
 - sudo apt install libgetdns-dev -y
 - dig @208.67.222.222 a.root-servers.net
 - cpanm --quiet --installdeps --notest Template
 - cpanm --quiet --installdeps --notest Swagger2::Markdown
script:
 - autoreconf -i
 - ./configure
 - make
 - cd regression-tests
 - ./runtests
 - cd ..
 - export WF_VERSION=`grep PACKAGE_VERSION Makefile | awk  '{ print $3}'`
 - git status
 - git status | grep -q clean
 - make dist
 - tar xvf wforce-$WF_VERSION.tar.gz
 - cd wforce-$WF_VERSION
 - autoreconf -i
 - ./configure
 - make
notifications:
  irc:
    channels:
      - "irc.oftc.net#dovepower"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
